# -*- mode: ruby -*-
# vi: set ft=ruby :

# Builds monroe-experiment-core from the repository.
# Builds the monroe-tap-agent files either from this folder or from the repository.
#
# IMPORTANT: Both options are DISABLED by default, uncomment one of the lines below
# (after [TAP AGENT]) to select which version to install

$build_from_local = <<SCRIPT
    echo "Build the Monroe-tap-agent (from the local version)"
    mkdir /source
    cp -r /vagrant/* /source/
    cd /source
    dos2unix ./build.sh ./opt/monroe/tap-agent/monroe-tap-agent
    ./build.sh  /source /deb_files
SCRIPT

$build_from_repo = <<SCRIPT
    echo "Build the Monroe-tap-agent (from repo)"
    cd schedulers/tap-agent
    ./build.sh  . /deb_files
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.name = "monroe-tap-agent"
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL

    echo "Install dependencies"
    sed -i -e 's/main/main non-free/g' /etc/apt/sources.list
    export DEBIAN_FRONTEND=noninteractive && apt-get update

    apt-get -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
            --no-install-recommends --no-install-suggests --allow-unauthenticated install \
            git curl jq ssh libuv1 libjson-c3 libjq1 libonig4 dnsutils dos2unix policykit-1 \
            apt-transport-https

    echo 'deb [trusted=yes] https://raw.githubusercontent.com/MONROE-PROJECT/apt-repo/master stretch main' > /etc/apt/sources.list.d/monroe.list

    mkdir /deb_files

    echo "Install docker"
    curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh

    echo "Build the Monroe-experiment-core (from repo)"
    git clone https://github.com/MONROE-PROJECT/monroe-experiment-core.git
    cd monroe-experiment-core
    ./build.sh  ./core /deb_files

    # [TAP AGENT]
    # Uncomment one of these lines to build the TAP agent
    # ---------------------------------------------------
    #   #{$build_from_local}
    #   #{$build_from_repo}
    # ---------------------------------------------------

    echo "Install deb files and clean-up"
    apt install -y /deb_files/*.deb
    rm -r /source
    rm -r /deb_files

    echo "Install certificates and start (from monroe-tap-agent.postinst)"
    openssl req -x509 -newkey rsa:4096 -nodes -out /opt/monroe/tap-agent/cert.pem -keyout /opt/monroe/tap-agent/key.pem -days 3650 -subj "/O=Monroe Project/CN=localhost"
    sed -i "s#TAP_AGENT_CERT=.*#TAP_AGENT_CERT=/opt/monroe/tap-agent/cert.pem#g" /opt/monroe/tap-agent/monroe-tap-agent
    sed -i "s#TAP_AGENT_KEY=.*#TAP_AGENT_KEY=/opt/monroe/tap-agent/key.pem#g" /opt/monroe/tap-agent/monroe-tap-agent

    systemctl enable monroe-tap-agent
    systemctl start  monroe-tap-agent

  SHELL
end
